name: SouthPlus签到

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install webdriver-manager   # 自动管理驱动

    - name: Install Chrome (latest stable)
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: 总脚本
      env:
        COOKIE: ${{ secrets.COOKIE }}
        serverKey: ${{ secrets.serverKey }}
        BOTTOKEN: ${{ secrets.BOTTOKEN }}
        CHATID: ${{ secrets.CHATID }}
      run: python byWebdrvier.py
